resolver 127.0.0.11 valid=10s;

server {
    listen 80;
    client_max_body_size 20M;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    set $backend_upstream ${BACKEND_URL};

    location /api/ {
        proxy_pass $backend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        proxy_pass $backend_upstream;
    }
}
